// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: has_permission.sql

package sqlc

import (
	"context"
)

const hasPermission = `-- name: HasPermission :one
SELECT EXISTS (
    SELECT 1
    FROM users usr
    INNER JOIN role_permissions rp
        ON usr.role_id = rp.role_id
    INNER JOIN permissions p
        ON rp.permission_id = p.id
    WHERE
        usr.id = $1
        AND p.resource = $2
        AND p.action = $3
) AS has_permission
`

type HasPermissionParams struct {
	UserID   int64  `json:"user_id"`
	Resource string `json:"resource"`
	Action   string `json:"action"`
}

func (q *Queries) HasPermission(ctx context.Context, arg HasPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasPermission, arg.UserID, arg.Resource, arg.Action)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}
