// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Permission struct {
	ID       int64       `json:"id"`
	Resource pgtype.Text `json:"resource"`
	Action   pgtype.Text `json:"action"`
}

type Role struct {
	ID   int64       `json:"id"`
	Name pgtype.Text `json:"name"`
}

type RolePermission struct {
	RoleID       int64 `json:"role_id"`
	PermissionID int64 `json:"permission_id"`
}

type User struct {
	ID   int64       `json:"id"`
	Name pgtype.Text `json:"name"`
}

type UserRole struct {
	UserID int64 `json:"user_id"`
	RoleID int64 `json:"role_id"`
}
