// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permission.sql

package sqlc

import (
	"context"
)

const createPermission = `-- name: CreatePermission :one
INSERT INTO permissions (
  resource, action
) VALUES (
  $1, $2
)
RETURNING id, resource, action, created_at, updated_at
`

type CreatePermissionParams struct {
	Resource string `json:"resource"`
	Action   string `json:"action"`
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permission, error) {
	row := q.db.QueryRow(ctx, createPermission, arg.Resource, arg.Action)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Resource,
		&i.Action,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePermission = `-- name: DeletePermission :exec
DELETE FROM permissions
WHERE id = $1
`

func (q *Queries) DeletePermission(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePermission, id)
	return err
}

const getPermission = `-- name: GetPermission :one
SELECT id, resource, action, created_at, updated_at FROM permissions
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPermission(ctx context.Context, id int64) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermission, id)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Resource,
		&i.Action,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPermission = `-- name: ListPermission :many
SELECT id, resource, action, created_at, updated_at FROM permissions
ORDER BY created_at
`

func (q *Queries) ListPermission(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermission)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Resource,
			&i.Action,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePermission = `-- name: UpdatePermission :exec
UPDATE permissions
  set resource = $2,
  action = $3
WHERE id = $1
`

type UpdatePermissionParams struct {
	ID       int64  `json:"id"`
	Resource string `json:"resource"`
	Action   string `json:"action"`
}

func (q *Queries) UpdatePermission(ctx context.Context, arg UpdatePermissionParams) error {
	_, err := q.db.Exec(ctx, updatePermission, arg.ID, arg.Resource, arg.Action)
	return err
}
