// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permissions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const hasPermission = `-- name: HasPermission :one
SELECT EXISTS (
    SELECT 1
    FROM user_roles ur
    INNER JOIN role_permissions rp
        ON ur.role_id = rp.role_id
    INNER JOIN permissions p
        ON rp.permission_id = p.id
    WHERE
        ur.user_id = $1
        AND p.resource = $2
        AND p.action = $3
) AS has_permission
`

type HasPermissionParams struct {
	UserID   int64       `json:"user_id"`
	Resource pgtype.Text `json:"resource"`
	Action   pgtype.Text `json:"action"`
}

func (q *Queries) HasPermission(ctx context.Context, arg HasPermissionParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasPermission, arg.UserID, arg.Resource, arg.Action)
	var has_permission bool
	err := row.Scan(&has_permission)
	return has_permission, err
}
