// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policy.sql

package sqlc

import (
	"context"
)

const getPolicies = `-- name: GetPolicies :many

SELECT
    p.effect,
    p.rules
FROM user_policy_assignments upa
JOIN policies p
    ON p.id = upa.policy_id
WHERE
    upa.user_id = $1
    AND upa.resource_id = $2

UNION ALL

SELECT
    p.effect,
    p.rules
FROM users u
JOIN role_policy_assignments rpa
    ON rpa.role_id = u.role_id
JOIN policies p
    ON p.id = rpa.policy_id
WHERE
    u.id = $1
    AND rpa.resource_id = $2
`

type GetPoliciesParams struct {
	UserID     int64 `json:"user_id"`
	ResourceID int64 `json:"resource_id"`
}

type GetPoliciesRow struct {
	Effect PolicyEffect `json:"effect"`
	Rules  []byte       `json:"rules"`
}

func (q *Queries) GetPolicies(ctx context.Context, arg GetPoliciesParams) ([]GetPoliciesRow, error) {
	rows, err := q.db.Query(ctx, getPolicies, arg.UserID, arg.ResourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPoliciesRow{}
	for rows.Next() {
		var i GetPoliciesRow
		if err := rows.Scan(&i.Effect, &i.Rules); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserHierarchy = `-- name: GetUserHierarchy :one

SELECT
    r.hierarchy
FROM users u
JOIN roles r
    ON r.id = u.role_id
WHERE
    u.id = $1
`

func (q *Queries) GetUserHierarchy(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getUserHierarchy, userID)
	var hierarchy int64
	err := row.Scan(&hierarchy)
	return hierarchy, err
}
