// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	HasPermission(ctx context.Context, arg HasPermissionParams) (bool, error)
}

var _ Querier = (*Queries)(nil)
