// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CreateResources(ctx context.Context, arg CreateResourcesParams) (Resource, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteResources(ctx context.Context, id int64) error
	DeleteRole(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetPolicies(ctx context.Context, arg GetPoliciesParams) ([]GetPoliciesRow, error)
	GetResources(ctx context.Context, id int64) (Resource, error)
	GetRole(ctx context.Context, id int64) (Role, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserHierarchy(ctx context.Context, userID int64) (int64, error)
	HasPermission(ctx context.Context, arg HasPermissionParams) (HasPermissionRow, error)
	ListResources(ctx context.Context) ([]Resource, error)
	ListRoles(ctx context.Context) ([]Role, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateResources(ctx context.Context, arg UpdateResourcesParams) error
	UpdateRole(ctx context.Context, arg UpdateRoleParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
