// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resources.sql

package sqlc

import (
	"context"
)

const createResources = `-- name: CreateResources :one
INSERT INTO resources (
  resource, action
) VALUES (
  $1, $2
)
RETURNING id, resource, action, created_at, updated_at
`

type CreateResourcesParams struct {
	Resource string `json:"resource"`
	Action   string `json:"action"`
}

func (q *Queries) CreateResources(ctx context.Context, arg CreateResourcesParams) (Resource, error) {
	row := q.db.QueryRow(ctx, createResources, arg.Resource, arg.Action)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Resource,
		&i.Action,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteResources = `-- name: DeleteResources :exec
DELETE FROM resources
WHERE id = $1
`

func (q *Queries) DeleteResources(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteResources, id)
	return err
}

const getResources = `-- name: GetResources :one
SELECT id, resource, action, created_at, updated_at FROM resources
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetResources(ctx context.Context, id int64) (Resource, error) {
	row := q.db.QueryRow(ctx, getResources, id)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.Resource,
		&i.Action,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listResources = `-- name: ListResources :many
SELECT id, resource, action, created_at, updated_at FROM resources
ORDER BY created_at
`

func (q *Queries) ListResources(ctx context.Context) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listResources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.Resource,
			&i.Action,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResources = `-- name: UpdateResources :exec
UPDATE resources
  set resource = $2,
  action = $3
WHERE id = $1
`

type UpdateResourcesParams struct {
	ID       int64  `json:"id"`
	Resource string `json:"resource"`
	Action   string `json:"action"`
}

func (q *Queries) UpdateResources(ctx context.Context, arg UpdateResourcesParams) error {
	_, err := q.db.Exec(ctx, updateResources, arg.ID, arg.Resource, arg.Action)
	return err
}
