// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  name, role_id
) VALUES (
  $1, $2
)
RETURNING id, name, role_id, office_id, department_id, report_to, created_at, updated_at
`

type CreateUserParams struct {
	Name   string      `json:"name"`
	RoleID pgtype.Int8 `json:"role_id"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.RoleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RoleID,
		&i.OfficeID,
		&i.DepartmentID,
		&i.ReportTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, name, role_id, office_id, department_id, report_to, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RoleID,
		&i.OfficeID,
		&i.DepartmentID,
		&i.ReportTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT
    u.id,
    u.name,
    u.role_id,
    u.office_id,
    u.department_id,
    u.report_to,
    u.created_at,
    u.updated_at
FROM users u
WHERE EXISTS (
    SELECT 1
        FROM filter_users(
        $1,
        $2,

        $3::bigint[],
        $4::bigint[],
        $5::bigint[],
        $6::text[],

        $7,
        $8
    ) f
    WHERE f.user_id = u.id
)
ORDER BY u.id DESC
`

type ListUsersParams struct {
	Scope           string      `json:"scope"`
	ManagerID       pgtype.Int8 `json:"manager_id"`
	OfficeIds       []int64     `json:"office_ids"`
	DepartmentIds   []int64     `json:"department_ids"`
	CompanyIds      []int64     `json:"company_ids"`
	EmploymentTypes []string    `json:"employment_types"`
	MyHierarchy     pgtype.Int8 `json:"my_hierarchy"`
	HierarchyMode   pgtype.Text `json:"hierarchy_mode"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Scope,
		arg.ManagerID,
		arg.OfficeIds,
		arg.DepartmentIds,
		arg.CompanyIds,
		arg.EmploymentTypes,
		arg.MyHierarchy,
		arg.HierarchyMode,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RoleID,
			&i.OfficeID,
			&i.DepartmentID,
			&i.ReportTo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
  set name = $2,
  role_id = $3
WHERE id = $1
`

type UpdateUserParams struct {
	ID     int64       `json:"id"`
	Name   string      `json:"name"`
	RoleID pgtype.Int8 `json:"role_id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser, arg.ID, arg.Name, arg.RoleID)
	return err
}
